In [82]:
import numpy as np
from collections import Counter

In [69]:
family = ['Dad', 'Mom', 'Mark', 'Adam', 'Sarah', 'Rachel', 'Matthew', 'Elizabeth']

In [70]:
def en(value):
    for counter, value in enumerate(family, 1):
        print (counter, value)

In [71]:
en(family)

1 Dad
2 Mom
3 Mark
4 Adam
5 Sarah
6 Rachel
7 Matthew
8 Elizabeth


In [75]:
from statistics import stdev

In [76]:
data = [90, 100, 110]
mu = 85
n = len(data)
s = stdev(data)
df = n-1

In [77]:
def ssd(lst):
    mean = sum(lst)/len(lst)
    sqrs=[]
    for i in lst:
        sqrs.append((i-mean)**2)
    return sum(sqrs)

In [78]:
def s_2(first, second):
    return (ssd(first) + ssd(second))/(len(first) + len(second) - 2)
    

In [79]:
s_squared = s_2(store1, store2)

NameError: name 'store1' is not defined

In [80]:
s_squared

NameError: name 's_squared' is not defined

In [81]:
store1 = [20, 30, 30, 50, 75, 25, 30, 30, 40, 80]
store2 = [60, 30, 70, 90, 60, 40, 70, 40]

In [8]:
store1_avg = sum(store1)/len(store1)
store2_avg = sum(store2)/len(store2)

In [9]:
store1_var = 

41.0

In [10]:
store2_avg

57.5

In [20]:
t = (store1_avg - store2_avg)/((s_squared/len(store1))+(s_squared/len(store2)))**.5

In [21]:
t

-1.70113828065953

In [2]:
import scipy.stats as stats

In [3]:
stats.norm.cdf(0)

0.5

In [4]:
stats.norm.cdf(1)

0.8413447460685429

In [5]:
stats.norm.cdf(1.96)

0.9750021048517795

In [6]:
stats.t.cdf(0, df = 20)

0.5

In [7]:
stats.t.cdf(2, df = 20)

0.9703672322767147

In [8]:
stats.norm.ppf(.5)

0.0

In [9]:
stats.norm.ppf(1)

inf

In [10]:
stats.norm.ppf(.99)

2.3263478740408408

In [11]:
stats.norm.ppf(.3
    )

-0.5244005127080409

In [12]:
stats.t.ppf(.90, 10)

1.3721836411102863

In [15]:
stats.t.ppf(.90, df = 10)

1.3721836411102863

In [18]:
xs = np.linspace(-5, 5, 200)

In [24]:
xs

array([-5.        , -4.94974874, -4.89949749, -4.84924623, -4.79899497,
       -4.74874372, -4.69849246, -4.64824121, -4.59798995, -4.54773869,
       -4.49748744, -4.44723618, -4.39698492, -4.34673367, -4.29648241,
       -4.24623116, -4.1959799 , -4.14572864, -4.09547739, -4.04522613,
       -3.99497487, -3.94472362, -3.89447236, -3.84422111, -3.79396985,
       -3.74371859, -3.69346734, -3.64321608, -3.59296482, -3.54271357,
       -3.49246231, -3.44221106, -3.3919598 , -3.34170854, -3.29145729,
       -3.24120603, -3.19095477, -3.14070352, -3.09045226, -3.04020101,
       -2.98994975, -2.93969849, -2.88944724, -2.83919598, -2.78894472,
       -2.73869347, -2.68844221, -2.63819095, -2.5879397 , -2.53768844,
       -2.48743719, -2.43718593, -2.38693467, -2.33668342, -2.28643216,
       -2.2361809 , -2.18592965, -2.13567839, -2.08542714, -2.03517588,
       -1.98492462, -1.93467337, -1.88442211, -1.83417085, -1.7839196 ,
       -1.73366834, -1.68341709, -1.63316583, -1.58291457, -1.53

In [19]:
ys = stats.t.pdf(xs, df, 0, 1)

NameError: name 'df' is not defined

In [27]:
string = "Ad____am"
string

'Ad____am'

In [28]:
list(string)

['A', 'd', '_', '_', '_', '_', 'a', 'm']

In [42]:
a = [1, 2, 3, 4]

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [30]:
numbers = np.array([2, 3, 4, 5, 6, 7])

In [31]:
num_2 = np.array([1, 2, 3, 46, 78, 1])

In [40]:
numbers**5

array([   32,   243,  1024,  3125,  7776, 16807])

In [45]:
min(a)

1

In [51]:
a = ['Mom', 'Dad', 'Matthew', 'Mark', 'Sarah', 'Adam']

In [52]:
max(a)

'Sarah'

In [60]:
a = str('home')

In [64]:
b = list(a)

In [65]:
b

['h', 'o', 'm', 'e']

In [66]:
b[0].title()

'H'

In [67]:
b

['h', 'o', 'm', 'e']

In [83]:
Counter(b)

Counter({'h': 1, 'o': 1, 'm': 1, 'e': 1})

In [84]:
a = [1, 2, 3, 4]

In [86]:
b = [1, 2, 3, 4]

In [87]:
set(a) == set(b)

True

In [88]:
def predict_y(X, w):
    return np.dot(X,w)

In [89]:
A = np.array([[1, 0, 1], [0, 1, 0], [2, 3, 4]])

In [95]:
A.shape[1]

3

In [100]:
b = np.array([[4],[5],[6]])

In [102]:
b

array([[4],
       [5],
       [6]])

In [107]:
b.shape

(3, 1)

In [104]:
c = b.flatten()

In [106]:
c.shape

(3,)

In [108]:
c

array([4, 5, 6])

In [109]:
len(c)

3

In [110]:
len(b)

3